pipeline {
    agent any
    
    environment {
        IMAGE_NAME = "your-dockerhub-username/your-app"
    }

    stages {
        stage('Build') {
            steps {
                script {
                    def buildDockerCompose = """
                    docker-compose -f docker-compose.override.yml -f docker-compose.yml build
                    """
                    bat buildDockerCompose
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    def runTests = """
                    docker-compose -f docker-compose.override.yml -f docker-compose.yml run --rm your-app-service dotnet test
                    """
                    bat runTests
                }
            }
        }
        
        stage('Push') {
            steps {
                script {
                    docker.withRegistry('', 'docker-hub-credentials') {
                        bat 'docker-compose -f docker-compose.override.yml -f docker-compose.yml push'
                    }
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    def deployDockerCompose = """
                    docker-compose -f docker-compose.override.yml -f docker-compose.yml up -d
                    """
                    bat deployDockerCompose
                }
            }
        }
    }
}
